### ISSUE TITLE
Open VSX release

### ISSUE THREAD

**Issue by ac130kz** [RobertBrunhage/flutter-riverpod-snippets#3]
VSCodium (a Microsoft free fork of VS Code) moved to Open VSX (a vendor-neutral repository) for extension distribution. It could be helpful for everyone, if the extension was published there as well.

[https://open-vsx.org/](https://open-vsx.org/)
[Guide ](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) how to publish on their repo

**Comment by ac130kz** [comment]
I've done a bit of research. There is a repository with an example [Github action](https://github.com/HaaLeo/publish-vscode-extension).

So far I think it needs an additional package:
```
      - uses: actions/setup-node@v1
        with:
          node-version: 12
```

And a new step for publishing:
```
 - uses: HaaLeo/publish-vscode-extension@v0
   id: publishToOpenVSX
   with:
     pat: ${{ secrets.OPEN_VSX_TOKEN }}
```
